language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-15
  - ANDROID_ABI=armeabi-v7a
notifications:
  slack:
    secure: FgBSftFVmF1XmiX8Lg713p7pyUmmlUT1IfBue/gW/skP/6grsUbDnr3SOKOJkobbWTQY+OOak9UdmdkeDmwn1HiE1MB7gY8z2gecSSIxo7xKl/ck0VtWIzOH/kkhOQVIJpI9fesA+uDZC2MCIVUwVG/IMTbt3P85YcuUQVwKrCBQeS8+Rg/pyQLtZK2b8z7/i3L8HcPjvoFpxkAEyT02HOZmNZJLU2jI0wobunUNTX9IiBYKXtgIx0UvEXb3t7MhIOihJlOefGdM57fr9r4gbyel9L3EYt+zUtWYnQqV54J1LikxbFQPf8/89JDBe8jYLmRxGrY87W58JALSlRUE5DxUgKudUp5indmxAVwFA0sghDJMHshtIWRDfyCw7vzo7TWj5bD40sAKc4xgi85b8uUyT4Mobtg/mK6CjNkfRZQWKN+jAto+HtqEokfTBThHXUIQEEPz4x8sMraormE2+Q+wUyD+iKx3vReGBlRhtkmFcQPXHR0IGiYOFzfGXRAOlHid9Br2ofj+MFUnkiIzerwkCsxGeqSrchtKu2KG3eNR5IpeK3oWnTQ6YbaJOd8cpXAN9bHNVuhiSoqdWjOztkM97UBBX6t3w2wlLz17RkFvtFxIkB3XHs/lwWlNcRcEmyRBN4Gdw83TtgE1o+/W2Vpy+34hmEKse33eOD5DWug=
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra-google-m2repository
  - sys-img-armeabi-v7a-android-19
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
before_install:
- pip install --user codecov
script:
- "./gradlew build jacocoTestReport"
- "./gradlew check"
after_success:
- "./gradlew jacocoFullReport"
- codecov
- bash <(curl -s https://codecov.io/bash)
